version: '3.6'
 
services:
  filebrowser:
    image: filebrowser/filebrowser:v2.9.0
    container_name: filebrowser
    ports:
      - "8080:8080" #SERVER_PORT
    restart: always
    volumes:
      - /mnt/movie:/srv/movie
      - .data/root:/srv
      - .data/database.db:/etc/database.db
      - ./data/.filebrowser.json:/.filebrowser.json