version: '3.6'
 
services:
  filebrowser:
    image: filebrowser/filebrowser:v2.9.0
    container_name: filebrowser
    ports:
      - "8080:8080" #SERVER_PORT
    restart: always
    volumes:
      - /mnt/movie:/srv/movie
      - /mnt/hentai:/srv/hentai
      - .data/root:/srv
      - .data/database.db:/etc/database.db
      - ./data/.filebrowser.json:/.filebrowser.json
  ariang:
    image: hurlenko/aria2-ariang
    ports:
      - 8081:8080
    volumes:
      - /mnt/hentai/download:/aria2/data
      - /CONFIG_DIR:/aria2/conf
    environment:
      - PUID=1000
      - PGID=1000
      - RPC_SECRET=secret
      - DOMAIN=0.0.0.0:8080
      - ARIA2RPCPORT=443
    restart: always